//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


CsvSchemaModeT = {
  'CsvSchemaModeNoneProvided' : 0,
  'CsvSchemaModeUseHeader' : 1,
  'CsvSchemaModeUseSchemaFile' : 2,
  'CsvSchemaModeUseLoadInput' : 3
};
CsvDialectT = {
  'CsvDialectDefault' : 0,
  'CsvDialectXcalarSnapshot' : 1
};
CsvSchemaModeTStr = {
  0 : 'none',
  1 : 'header',
  2 : 'schemaFile',
  3 : 'loadInput'
};
CsvSchemaModeTFromStr = {
  'none' : 0,
  'header' : 1,
  'schemaFile' : 2,
  'loadInput' : 3
};
CsvDialectTStr = {
  0 : 'default',
  1 : 'xcalarSnapshot'
};
CsvDialectTFromStr = {
  'default' : 0,
  'xcalarSnapshot' : 1
};
