//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


DagRefTypeT = {
  'DagRefNone' : 0,
  'DagRefApi' : 1,
  'DagRefOperator' : 2,
  'DagRefNode' : 3,
  'DagRefResultSet' : 4
};
DagRefTypeTStr = {
  0 : 'None',
  1 : 'api',
  2 : 'operator',
  3 : 'dag node',
  4 : 'result set'
};
DagRefTypeTFromStr = {
  'None' : 0,
  'api' : 1,
  'operator' : 2,
  'dag node' : 3,
  'result set' : 4
};
