//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


DgDagStateT = {
  'DgDagStateUnknown' : 0,
  'DgDagStateCreated' : 1,
  'DgDagStateQueued' : 2,
  'DgDagStateProcessing' : 3,
  'DgDagStateCleaned' : 4,
  'DgDagStateReady' : 5,
  'DgDagStateDropped' : 6,
  'DgDagStateError' : 7,
  'DgDagStateArchived' : 8,
  'DgDagStateArchiving' : 9,
  'DgDagStateArchiveError' : 10
};
DgDagStateTStr = {
  0 : 'Unknown state',
  1 : 'Created',
  2 : 'Queued',
  3 : 'Processing',
  4 : 'Cleaned',
  5 : 'Ready',
  6 : 'Dropped',
  7 : 'Error',
  8 : 'Archived',
  9 : 'Archiving',
  10 : 'Error during Archiving'
};
DgDagStateTFromStr = {
  'Unknown state' : 0,
  'Created' : 1,
  'Queued' : 2,
  'Processing' : 3,
  'Cleaned' : 4,
  'Ready' : 5,
  'Dropped' : 6,
  'Error' : 7,
  'Archived' : 8,
  'Archiving' : 9,
  'Error during Archiving' : 10
};
