//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


DfFieldTypeT = {
  'DfUnknown' : 0,
  'DfString' : 1,
  'DfInt32' : 2,
  'DfUInt32' : 3,
  'DfInt64' : 4,
  'DfUInt64' : 5,
  'DfFloat32' : 6,
  'DfFloat64' : 7,
  'DfBoolean' : 8,
  'DfTimespec' : 9,
  'DfBlob' : 10,
  'DfNull' : 11,
  'DfMixed' : 12,
  'DfFatptr' : 13,
  'DfScalarPtr' : 14,
  'DfScalarObj' : 15,
  'DfOpRowMetaPtr' : 16,
  'DfArray' : 17,
  'DfObject' : 18,
  'DfMoney' : 19
};
DfFormatTypeT = {
  'DfFormatUnknown' : 0,
  'DfFormatJson' : 1,
  'DfFormatCsv' : 2,
  'DfFormatSql' : 3,
  'DfFormatInternal' : 4,
  'DfFormatParquet' : 5
};
DfFieldTypeTStr = {
  0 : 'DfUnknown',
  1 : 'DfString',
  2 : 'DfInt32',
  3 : 'DfUInt32',
  4 : 'DfInt64',
  5 : 'DfUInt64',
  6 : 'DfFloat32',
  7 : 'DfFloat64',
  8 : 'DfBoolean',
  9 : 'DfTimespec',
  10 : 'DfBlob',
  11 : 'DfNull',
  12 : 'DfMixed',
  13 : 'DfFatptr',
  14 : 'DfScalarPtr',
  15 : 'DfScalarObj',
  16 : 'DfOpRowMetaPtr',
  17 : 'DfArray',
  18 : 'DfObject',
  19 : 'DfMoney'
};
DfFieldTypeTFromStr = {
  'DfUnknown' : 0,
  'DfString' : 1,
  'DfInt32' : 2,
  'DfUInt32' : 3,
  'DfInt64' : 4,
  'DfUInt64' : 5,
  'DfFloat32' : 6,
  'DfFloat64' : 7,
  'DfBoolean' : 8,
  'DfTimespec' : 9,
  'DfBlob' : 10,
  'DfNull' : 11,
  'DfMixed' : 12,
  'DfFatptr' : 13,
  'DfScalarPtr' : 14,
  'DfScalarObj' : 15,
  'DfOpRowMetaPtr' : 16,
  'DfArray' : 17,
  'DfObject' : 18,
  'DfMoney' : 19
};
DfFormatTypeTStr = {
  0 : 'unknown',
  1 : 'json',
  2 : 'csv',
  3 : 'sql',
  4 : 'internal',
  5 : 'parquet'
};
DfFormatTypeTFromStr = {
  'unknown' : 0,
  'json' : 1,
  'csv' : 2,
  'sql' : 3,
  'internal' : 4,
  'parquet' : 5
};
