//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


FunctionCategoryT = {
  'FunctionCategoryArithmetic' : 0,
  'FunctionCategoryBitwise' : 1,
  'FunctionCategoryTrigonometry' : 2,
  'FunctionCategoryConversion' : 3,
  'FunctionCategoryString' : 4,
  'FunctionCategoryMisc' : 5,
  'FunctionCategoryCondition' : 6,
  'FunctionCategoryAggregate' : 7,
  'FunctionCategoryCast' : 8,
  'FunctionCategoryUdf' : 9,
  'FunctionCategoryTimestamp' : 10
};
FunctionCategoryTStr = {
  0 : 'Arithmetic functions',
  1 : 'Bitwise functions',
  2 : 'Trigonometric functions',
  3 : 'Conversion functions',
  4 : 'String functions',
  5 : 'Miscellaneous functions',
  6 : 'Conditional functions',
  7 : 'Aggregate functions',
  8 : 'Type-casting functions',
  9 : 'User-defined functions',
  10 : 'Timestamp functions'
};
FunctionCategoryTFromStr = {
  'Arithmetic functions' : 0,
  'Bitwise functions' : 1,
  'Trigonometric functions' : 2,
  'Conversion functions' : 3,
  'String functions' : 4,
  'Miscellaneous functions' : 5,
  'Conditional functions' : 6,
  'Aggregate functions' : 7,
  'Type-casting functions' : 8,
  'User-defined functions' : 9,
  'Timestamp functions' : 10
};
