//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarOrderingT = {
  'XcalarOrderingUnordered' : 0,
  'XcalarOrderingAscending' : 3,
  'XcalarOrderingDescending' : 5,
  'XcalarOrderingPartialAscending' : 11,
  'XcalarOrderingPartialDescending' : 13,
  'XcalarOrderingRandom' : 16,
  'XcalarOrderingInvalid' : 195936478
};
XcalarOrderingTStr = {
  0 : 'Unordered',
  3 : 'Ascending',
  5 : 'Descending',
  11 : 'PartialAscending',
  13 : 'PartialDescending',
  16 : 'Random',
  195936478 : 'Invalid'
};
XcalarOrderingTFromStr = {
  'Unordered' : 0,
  'Ascending' : 3,
  'Descending' : 5,
  'PartialAscending' : 11,
  'PartialDescending' : 13,
  'Random' : 16,
  'Invalid' : 195936478
};
