//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


QueryStateT = {
  'qrNotStarted' : 0,
  'qrProcessing' : 1,
  'qrFinished' : 2,
  'qrError' : 3,
  'qrCancelled' : 4
};
QueryStateTStr = {
  0 : 'qrNotStarted',
  1 : 'qrProcessing',
  2 : 'qrFinished',
  3 : 'qrError',
  4 : 'qrCancelled'
};
QueryStateTFromStr = {
  'qrNotStarted' : 0,
  'qrProcessing' : 1,
  'qrFinished' : 2,
  'qrError' : 3,
  'qrCancelled' : 4
};
