//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


UnionOperatorT = {
  'UnionStandard' : 0,
  'UnionIntersect' : 1,
  'UnionExcept' : 2
};
UnionOperatorTStr = {
  0 : 'unionStandard',
  1 : 'unionIntersect',
  2 : 'unionExcept'
};
UnionOperatorTFromStr = {
  'unionStandard' : 0,
  'unionIntersect' : 1,
  'unionExcept' : 2
};
