//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarEvalArgTypeT = {
  'OptionalArg' : 0,
  'RequiredArg' : 1,
  'VariableArg' : 2
};
AccumulatorTypeT = {
  'AccumulatorMax' : 0,
  'AccumulatorMin' : 1,
  'AccumulatorCount' : 2,
  'AccumulatorAvg' : 3,
  'AccumulatorAvgNumeric' : 4,
  'AccumulatorSumFloat' : 5,
  'AccumulatorSumInteger' : 6,
  'AccumulatorSumNumeric' : 7
};
XcalarEvalArgTypeTStr = {
  0 : 'optional',
  1 : 'required',
  2 : 'variable'
};
XcalarEvalArgTypeTFromStr = {
  'optional' : 0,
  'required' : 1,
  'variable' : 2
};
AccumulatorTypeTStr = {
  0 : 'max',
  1 : 'min',
  2 : 'count',
  3 : 'avg',
  4 : 'avgNumeric',
  5 : 'sum',
  6 : 'sumInteger',
  7 : 'sumNumeric'
};
AccumulatorTypeTFromStr = {
  'max' : 0,
  'min' : 1,
  'count' : 2,
  'avg' : 3,
  'avgNumeric' : 4,
  'sum' : 5,
  'sumInteger' : 6,
  'sumNumeric' : 7
};
