//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarApiVersionT = {
  'XcalarApiVersionSignature' : 21322193
};
XcalarApiVersionTStr = {
  21322193 : '14559d10ca8820b06efdb214d0bc1edc'
};
XcalarApiVersionTFromStr = {
  '14559d10ca8820b06efdb214d0bc1edc' : 21322193
};
